In [1]:
from numpy import *
from scipy import *
import numpy as np
from matplotlib import *

from scipy import integrate
from scipy import interpolate
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

import xlrd

rc('text',usetex = True)
rc('font', family='serif',size = 12)

In [29]:
Data = xlrd.open_workbook('AMR_Inputs.xlsx')
Eff = Data.sheet_by_name('Eff') 
Effect = []

for i in range(7):
     Effect.append(array(Eff.col_values(i)))

phi = np.arange(0.1,2.01,0.1)
NTU = np.arange(50,351,50)
NN,PP = np.meshgrid(NTU,phi)
Effectiv = interpolate.interp2d(phi,NTU,Effect,kind = 'linear')

In [2]:
def R4(X): 
    R2,R3,B = X
    return (1.27708795*(R2**-1.18177842)*(R3**2.14218804)*(B**0.70136265))

In [3]:
def Qc(X): 
    P1,P2,P3,P4,P5= X #Q_pas_CB,Q_act_CB,Q_span,W_mag,W_p
    return (2.22068098*P1+0.52868254*P2+-2.22664497*P3+-0.02146037*P4+-5.09505357*P5)

In [4]:
def Qh(X): 
    P1,P2,P3,P4,P5= X
    return (2.77459330e+00*P1+1.28933075e+00*P2-2.79557285e+00*P3+1.29594714e-03*P4-4.39735607e+00*P5)

In [5]:
def W_Hex(X):
    P1,P2 = X
    return (a*P1**b + c*P2**d)

In [11]:
def Prop_param(X):
    T_c,T_h,B = X
    C_H = 1.65161038/100*T_c+2.59946197*T_h-1.14324309*100*B
    C_L = 10.16443738*T_c-5.32568341*T_h-0.71305997*B
    dT_mg = -0.01057708*T_c+0.01163704*T_h+1.73509682*B
    dT_dmg = -0.01229483*T_c+0.01376157*T_h+0.76454655*B
    CdT_mg = -9.517569*T_c+11.49711993*T_h+820.04168503*B
    CdT_dmg = 4.39480124*T_c-7.07931118/10*T_h+9.15928168*100*B
    return(C_H,C_L,dT_mg,dT_dmg,CdT_mg,CdT_dmg)

Calculation

In [120]:
def Optimal(m_f,FE,f,L,H,W,B,Qc_target,Tc,Th,Tce,The):
    
    ##Properties of the solid 
    rho_s = 7900  #[kg/m3] Density of the solid
    k_s   = 8 #[W/(m2.K)] #Thermal conductivity of the solid

    ## Propertis of the fluid
    rho_f = 1000  #[kg/m3] Density of the fluid
    c_f   = 4181  #[kJ/(kg.K)] # Specific heat of the fluid
    Pr_f  = 6.136 #[-] Prandtl of the fluid
    mu_f  = 0.00061 #0.0008901 #[kg/m-2] #Viscosity of the fluid
    k_f   = 0.6065  #[W/(m2.K)] #Thermal conductivity of the fluid

    ## Porous medium
    d_p = 500*10**(-6) #[m] Particle diameter
    Epsilon = 0.45  #[-] Porosity

    #Magnetic Circuit
    B_rem = 1.35
    N_p = 2
    N_Rp = 2
    
    ### CALCULATION ###
    
    #Porous medium
    m_s   = L*W*H*10**-9*(1-Epsilon)*rho_s #mass of the AMR
    Beta = (1-Epsilon)*6/d_p
    v_s   = (m_f)/(rho_f*W*H*10**-6) #Superficial velocity

    #Dimensionless Numbers
    Re_dp = d_p*v_s*rho_f/((1-Epsilon)*mu_f) #Reynolds number
    Nu = 2*(1+4*(1-Epsilon)/Epsilon)+((1-Epsilon)**0.5)*Re_dp**0.6*Pr_f**(1/3) # Nusselt number
    Pe = Re_dp*Pr_f
    h_int = Nu*k_f/d_p
    NTU_f  = h_int*Beta*(L*W*H*10**(-9))/(m_f*c_f) 
    dP = (L/1000)*(150*(1-Epsilon)**2*mu_f*v_s/(Epsilon**3*d_p**2) + 1.75*(1-Epsilon)*rho_f*v_s**2/(Epsilon**3*d_p))

    #Effective conduction
    k_e_f = k_f*Epsilon #Fluid effective conduction

    a_0 = exp(-1.084-6.778*(Epsilon-0.298))
    f_0 = 0.8
    k_e_s = k_f*((1-a_0)*(Epsilon*f_0+(1-Epsilon*f_0)*k_s/k_f)/(1-Epsilon*(1-f_0)+k_s/k_f*Epsilon*(1-f_0))+a_0*(2*((k_s/k_f)**2)*(1-Epsilon)+(1+2*Epsilon)*k_s/k_f)/((2+Epsilon)*k_s/k_f+(1-Epsilon))) #Solid effective conduction

    D_ = (k_f*rho_f/c_f)*0.75*Pe/2

    k_s_eff = k_e_s
    k_f_eff = k_e_f + rho_f*c_f*D_
    
    ##### Properties Calculation ######
    
    C_H,C_L,dT_mg,dT_dmg,CdT_mg,CdT_dmg = Prop_param((Tce,The,B))
    
    ##### Porous media effectivness #####
    
    Pi_6 = ((m_f)*c_f)/(m_s*C_L*f)
    Pi_4 = CdT_mg/CdT_dmg

    Efness_HB = Effectiv(Pi_6/2,NTU_f)
    Efness_CB = Effectiv(Pi_6/(2*Pi_4),NTU_f)

    
    ## Metrics ##
    
    Q_pas_CB = Efness_CB*(The - Tce)*m_f*FE*c_f
    Q_act_CB = dT_mg*m_f*c_f*FE

    Q_pas_HB = Efness_HB*(The - Tce)*m_f*FE*c_f
    Q_act_HB = dT_dmg*m_f*c_f*FE

    Q_span = (The - Tce)*m_f*c_f*FE
    print(The-Tce,m_f*3600,c_f,FE)
    Q_cond = ((1-Epsilon)*k_s_eff + Epsilon*k_f_eff)*(W*H*10**-6)*(The-Tce)/L
    W_mag  = m_s*f*(CdT_mg - CdT_dmg)
    W_pump = dP*m_f/rho_f*2*(FE)
    
    print(Q_pas_CB,Q_act_CB,Q_span,W_mag,W_pump)
    
    ######Calculation#######
    
    Qc_reg = Qc((Q_pas_CB,Q_act_CB,Q_span,W_mag,W_pump))
    Qh_reg = Qh((Q_pas_HB,Q_act_HB,Q_span,W_mag,W_pump))
    
    N_reg = Qc_target/Qc_reg
    Qh_target= Qh_reg*N_reg
    
    ECr_c = Qc_target/(FE*N_reg*m_f*c_f*(Tc-Tce))
    ECr_h = Qh_target/(FE*N_reg*m_f*c_f*(The-Th))
    
    T_CHex = Tce + Qc_target/(FE*N_reg*m_f*c_f) - 273.15
    T_HHex = The - Qh_target/(FE*N_reg*m_f*c_f) - 273.15
    
    return (Qc_reg,Qh_reg,N_reg,ECr_c,ECr_h,T_CHex,T_HHex,dP)

In [121]:
Optimal(800/3600,0.25,3,160,30,60,1.5,2650,22+273.15,35+273.15,14+273.15,43+273.15)

29.0 800.0 4181 0.25
[6601.56396771] 753.6222080902222 6736.055555555555 -1051.6677836679357 8.390634724535698


(array([39.40867045]),
 array([40.00151477]),
 array([67.24408536]),
 array([0.02120773]),
 array([0.02152677]),
 array([14.16966182]),
 array([42.82778587]),
 75515.71252082128)

In [ ]:
Pi_6 = ((m_f)*c_f)/(m_s*C_L*f)

Efness_HB = zeros(len(Pi_6))
Efness_CB = zeros(len(Pi_6))

for i in range(len(Pi_6)):
    Efness_HB[i] = Effectiv(Pi_6[i]/2,NTU_f[i])
    Efness_CB[i] = Effectiv(Pi_6[i]/(2*Pi_4[i]),NTU_f[i])


Q_pas_CB = Efness_CB*(T_h - T_c)*m_f*FE*c_f
Q_act_CB = dT_mg*m_f*c_f*FE

Q_pas_HB = Efness_HB*(T_h - T_c)*m_f*FE*c_f
Q_act_HB = dT_dmg*m_f*c_f*FE

Q_span = (T_h - T_c)*m_f*c_f*FE
Q_cond = ((1-Epsilon)*k_s_eff + Epsilon*k_f_eff)*(W*H*10**-6)*(T_h-T_c)/L
W_mag  = m_s*f*(CdT_mg - CdT_dmg)

### Closure Relations

Regenerator arranges

In [9]:
N_arr = 1/FE
N_r = N_Rp*N_p*N_arr

NameError: name 'FE' is not defined

Heat Exchangers

In [ ]:
ECr_h = Q_h/(m_f*c_f*(T_he - T_h))
ECr_c = Q_c/(m_f*c_f*(T_c - T_ce))